name: m3o
version: 1.0.43
homepage: https://github.com/m3o/m3o-dart
description: This is the Dart client to access APIs on the M3O Platform

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  freezed: ^1.1.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.3
  
dependencies: 
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0