name: Update Changelog and Publish

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          path: m3o-dart

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          path-to-changelog:  '/github/workspace/m3o-dart/CHANGELOG.md'

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          cwd: m3o-dart
          message: Update CHANGELOG
          pathspec_error_handling: exitImmediately

      - name: publish m3o-dart package
        uses: m3o/m3o-publish-dart-action@main
        with:
          pub_credentials: ${{ secrets.CREDENTIAL_JSON }}
    
